### ISSUE TITLE
Project Init.

### ISSUE THREAD

**Issue by that-jpg** [that-jpg/mh#4]
We need to create the projects empty structure to make the CI/CD work. This should be a feature by itself (?)

**Comment by that-jpg** [comment]
Now that the project have some code, let's config the CI/CD.

**Comment by that-jpg** [comment]
Tests are now working on both backend and front, everything running smoothly

**Comment by that-jpg** [comment]
https://github.com/that-jpg/mh/pull/5

**Comment by that-jpg** [comment]
https://github.com/that-jpg/mh/pull/6

**Comment by that-jpg** [comment]
https://github.com/that-jpg/mh/pull/8

**Comment by that-jpg** [comment]
https://github.com/that-jpg/mh/pull/9

**Comment by brenofranca83** [comment]
Evitem abrir inúmeros PRs para a mesma feature. Façam PR apenas quando a feature estiver finalizada.
